@startuml
Actor "actorName" as A

box "Manage-Stack-Template" #lightblue
participant CLI as CLI
participant Web as Web
participant "c3" as S
A -> CLI : c3-template-create()
CLI -> S : template/create()
A -> Web : template/create()
Web -> S : template/create()
end box

@enduml
