@startuml
Actor "actorName" as A

box "Manage-Stack-Template" #lightblue
participant CLI as CLI
participant Web as Web
participant "c3" as S
A -> CLI : c3-template-test()
CLI -> S : template/test()
A -> Web : template/test()
Web -> S : template/test()
end box

@enduml
