servicelets:
    -
        name: web
        stacklet: 294
        args: null
        template: 926
        expose: null
        linkNames:
            - redis
            - mongo
        createdAt: '2017-05-13T01:04:48.306Z'
        updatedAt: '2017-05-13T01:05:49.600Z'
        id: 305
    -
        name: redis
        stacklet: 294
        args: null
        template: 924
        expose: null
        linkNames: null
        createdAt: '2017-05-13T01:04:48.308Z'
        updatedAt: '2017-05-13T01:05:49.603Z'
        id: 306
    -
        name: mongo
        stacklet: 294
        args: null
        template: 925
        expose: null
        linkNames: null
        createdAt: '2017-05-13T01:04:48.311Z'
        updatedAt: '2017-05-13T01:05:49.606Z'
        id: 307
env:
    name: Local
    createdAt: '2017-05-13T01:04:22.689Z'
    updatedAt: '2017-05-13T01:04:22.689Z'
    id: 343
stack:
    isFulfilled: false
    isRejected: false
name: NodeJS
createdAt: '2017-05-13T01:05:49.521Z'
updatedAt: '2017-05-13T01:05:49.621Z'
id: 294
