@startuml

package "EnvironmentManager" {
  interface "EnvironmentManager" {
  }
}

CLI ()-- "EnvironmentManager"
"REST API" ()-- "EnvironmentManager"
"Web Portal" ()-- "EnvironmentManager"


@enduml
