@startuml
Actor "actorName" as A

box "Manage-Service-Template" #lightblue
participant CLI as CLI
participant Web as Web
participant "c3" as S
A -> CLI : c3-template-enable()
CLI -> S : template/enable()
A -> Web : template/enable()
Web -> S : template/enable()
end box

@enduml
