@startuml
Actor "actorName" as A

box "Manage-Service-Template" #lightblue
participant CLI as CLI
participant Web as Web
participant "c3" as S
A -> CLI : c3-template-get()
CLI -> S : template/get()
A -> Web : template/get()
Web -> S : template/get()
end box

@enduml
