@startuml
Actor "Stack Developer"

"Stack Developer" -> "Operations Manager" : updateServiceTemplate(name, yaml)
activate "Operations Manager"
"Operations Manager" -> "Operations Manager" :findServiceTemplate(name) : appStack
alt not found
create "Service Template"
"Operations Manager" -> "Service Template" : new(name, yaml)
else
"Operations Manager" -> "Service Template" : update(yaml)
end
@enduml
