@startuml
Actor "Application Developer"

"Application Developer" -> "Artifact Repository" : deployApplication(name, yaml)
activate "Artifact Repository"
"Artifact Repository" -> "Artifact Repsoitory" :findApplication(name)
alt not found
create Application
"Artifact Repository" -> "Application" : new(name, appStack, yaml)
else
"Artifact Repository" -> "Application" : update(yaml
end
deactivate "Artifact Repository"
@enduml
