@startuml


package  common-cloud-core #lightgray {
  interface CLI
  interface Web
  interface REST
  package Portal #lightblue {
    component portal
    component applicationManager
    component stackManager
    component operationsManager
  }
  package Orchestrator #pink {
    component applicationOrchestrator
    component environmentManager
    component policyManager
    component applicationAnalytics
  }
  package "Registry" #lightgreen {
    component identityManager
    component artifactRepository
    database "identityRepo"
    database "artifactRepo"
  }
  package "Control" #lightyellow {
    component cloudBroker
    component dataCoordinator
    component provisionEngine
  }
}

rectangle ports {
    80 .. Web
    5432 .. REST
}

identityManager -- identityRepo
artifactRepository -- artifactRepo

CLI -- portal
Web -- portal
REST -- portal

portal -- applicationManager
portal -- stackManager
portal -- operationsManager
@enduml

