name: NodeJS
version: 0.0.1
environment: Local
Services:
  web:
    ports: 1337
    expose: 1337
    parameters:
      - name: MyName
      - location: MyLocation
  redis:
    ports: 6379
  mongo:
    ports: 27017
