@startuml
cloud Test {
    node LoadBalancer {
      component NGNX
      80 - NGNX
    }
    node iNodeJS1 {
      component NodeJS1
      8081 - NodeJS1
    }
     node iNodeJS2 {
      component NodeJS2
      8080 - NodeJS2
    }
    NGNX --> 8081
    NGNX --> 8080
    node iRedis1 {
      component Redis1
      6379 - Redis1
    }
    node iRedis2 {
      component Redis2
      6380 - Redis2
    }
    node iMongo {
      database Mongo
      27017 - Mongo
    }

    NodeJS1 --> 27017
    NodeJS2 --> 27017
    NodeJS1 --> 6379
    NodeJS2 --> 6379
    NodeJS1 --> 6380
    NodeJS2 --> 6380
}
Developer --> 80
@enduml

