@startuml
|Operations Manager|
start
|#ffffaa|common-cloud-core|
:Create Policy;
:Check Policy;
if(check) then (failed)
:Update Policy;
endif
:Enable Policy;
|Operations Manager|
stop
start
:Disable Policy;
:Check Policy;
:Delete Policy;
@enduml
