@startuml

left to right direction

actor :Operations Manager: as Ops
actor :Application Orchestrator: as AO
actor :Private Cloud: as PC1
actor :Public Cloud: as PC2

rectangle "Cloud Broker" #lightblue {
    UseCase UC1 as "Manage Infrastructure"
    UseCase UC2 as "Manage Cloud"
    UseCase UC3 as "Request Resources"
    Ops --> UC1
    Ops --> UC2
    UC1 --> PC1
    UC1 --> PC2
    UC3 --> PC1
    UC3 --> PC2
    AO --> UC3
}

@enduml
