@startuml
Actor "Application Developer"

"Application Developer" -> "Application Manager" : runCommand(environment, service)
activate "Application Manager"
"Application Manager" -> "Application Manager" :findApplicationStack(name) : appStack
"Application Manager" -> "Application Manager" :findServiceInEnvironment(service, environment) : serviceInstance
"Application Manager" -> "ProvisionEngine" : runCommandWithService(command, ServiceInstance)
deactivate "Application Manager"

@enduml
