@startuml

package "Composite Templates" {
  component "Oracle"
  component "Sql Server"
  Component "* MYSql"
  component "* Redis"
  component "* NodeJS"
}

package "Environment" {
  interface "Dev"
  interface "Test"
  interface "Production"
  interface "HA Production"
}

package "Application Stacks" {
    component "Get Started App"
    component "* NodeJS App Stack"
    component "JVM App Stack"
}

@enduml
