@startuml
Actor "Operations Engineer"

"Operations Engineer" -> "Operations Manager" : removePolicy(name, yaml)
activate "Operations Manager"
"Operations Manager" -> "Operations Manager" :findPolicy(name) : Policy
alt found
"Operations Manager" -> "Policy" : remove(name)
destroy "Policy"
end
@enduml
