@startuml
Actor "actorName" as A

box "Manage-Policies" #lightblue
participant CLI as CLI
participant Web as Web
participant "c3" as S
A -> CLI : c3-policy-enable(name)
CLI -> S : policy/enable(name)
A -> Web : policy/enable(name)
Web -> S : policy/enable(name)
end box

@enduml
