@startuml
|Operations Manager|
start
|#aaffff|c3|
:Create Cloud;
:List Clouds;
:Update Cloud;
fork
:Map Images to Cloud;
fork again
:Map Resources to Cloud;
fork again
:Map Machine Types to Cloud;
end fork
:Remove Cloud;
stop
@enduml
