@startuml
|Application Developer|
start
|#aaaaff|Artifact Repository|
:Browse Artifact Repository;
:Select Application Stack;
|Application Developer|
:Create Working Direectory;
|#aaffff|Application Manager|
:Create Application;
:Modify Application Definition;
|Application Developer|
:Modify Code;
|Application Manager|
if(try local) then (yes)
:Launch Application\nin Local Environment;
:Get Logs;
:Kill Application;
elseif(collab with dev) then (yes)
:Launch Application\nin Dev Environment;
:Get Logs;
:Debug Application;
:Kill Application;
elseif(ready to test) then (yes)
:Launch Application\nin Test Environment;
:Run Test;
:Get Logs;
:Debug Application;
:Kill Application;
elseif(ready to deploy) then (yes)
:Launch Application\nin Production Environment;
|Application Developer|
endif
stop
@enduml

