@startuml
cloud Production {
    package NodeJS {
        node LoadBalancer {
          component NGNX
          80 - NGNX
        }
        node iNodeJS1 {
          8081 - NodeJS1A
        }
        node iNodeJS2 {
          component NodeJS2
          8080 - NodeJS2
        }
        node iNodeJS3 {
          component NodeJS3
          8082 - NodeJS3
        }
        NGNX --> 8082
        NGNX --> 8081
        NGNX --> 8080
    }
    package iRedis {
      node RedisHA {
          component Redis
          6379 - Redis
      }
      node iRedis1 {
          component Redis1
          6380 - Redis1
      }
      node iRedis2 {
          component Redis2
          6381 - Redis2
      }
      Redis --> 6380
      Redis --> 6381
    }
    package iMongo {
      node MongoHA {
        component Mongo
        27017 - Mongo
      }
      node iMongoA {
         database MongoA
         27018 - MongoA
      }
      node iMongoB {
         database MongoB
         27019 - MongoB
      }
      node iMongoC {
         database MongoC
         27020 - MongoC
      }
      Mongo --> 27018
      Mongo --> 27019
      Mongo --> 27020
    }
    NodeJS ==> 6379
    NodeJS ==> 27017
}
Developer --> 80
@enduml

