@startuml
Actor "actorName" as A

box "Manage-Application-Stack" #lightblue
participant CLI as CLI
participant Web as Web
participant "c3" as S
A -> CLI : c3-stack-debug()
CLI -> S : stack/debug()
A -> Web : stack/debug()
Web -> S : stack/debug()
end box

@enduml
