@startuml

package "app-analyzer" #lightblue {
    interface "app-analyzer" {

    }
    CLI ()-- "app-analyzer" : 5000
    REST ()-- "app-analyzer" : 3000
    Web ()-- "app-analyzer" : 80
}


@enduml
