@startuml
|Developer|
start
|#lightblue|Common Cloud Core|
if(Application exists) then (no)
:Create Application;
endif
:Get Application;
:Launch Application;
while(has bug?)
:Debug Application;
:Run Command;
endwhile
:Publish Application;
:Deploy Application;
|#lightgreen|cloud|
:spin up Application;
stop
@enduml
