@startuml
|actorName|
start
|#ffffaa|c3|
:Create Application;
:Debug Application;
:Deploy Application;
:Check Application Health;
:Kill Application;
:List Application;
:Publish Application;
:Run Command;
stop
@enduml
