@startuml
|Developer|
start
|#aaffaa|Common Cloud Core|
if(Application exists) then (no)
:Create Application;
endif
:Get Application;
:Launch Application;
while(has bug?)
:Debug Application;
:Run Command;
endwhile
:Publish Application;
:Deploy Application;
|cloud|
:activity2;
stop
@enduml
