@startuml
Actor "actorName" as A

box "Manage-Applications" #lightblue
participant CLI as CLI
participant Web as Web
participant "c3" as S
A -> CLI : c3-app-destroy()
CLI -> S : app/destroy()
A -> Web : app/destroy()
Web -> S : app/destroy()
end box

@enduml
