@startuml

Developer -> ApplicationManager: launchApplication(String name, Map config)
activate ApplicationManager

ApplicationManager -> Application : load()
activate Application
ApplicationManager -> Application : ServiceGraph getServiceGraph()
deactivate Application

ApplicationManager -> ApplicationOrchestration : void launchServices(ServiceGraph sgraph)
activate ApplicationOrchestration

ApplicationOrchestration -> PolicyManager : ExecutionGraph injectPolicies(ServiceGraph sgraph)
loop #lightblue ExecutionGraph
    ApplicationOrchestration -> CloudBroker : findCloud(ExecutionItem item)
    ApplicationOrchestration -\ DataCoordinator : syncImage(Image image, SDI)
    ApplicationOrchestration -\ DataCoordinator : syncData(Service service, SDI)
    ApplicationOrchestration -> SDIOrchestration : startService(Service service, Policy policy, Image image)
    activate SDIOrchestration
    ApplicationOrchestration -\ SDIOrchestration : watchService(Service service)
    SDIOrchestration -\ ApplicationOrchestration : servicePreReady
    deactivate SDIOrchestration
    ApplicationOrchestration -\ Provisioner : buildService
    activate Provisioner
    Provisioner -> ServiceInstance : provision(Software, Config)
    ServiceInstance -> Provisioner : serviceReady
    Provisioner -\ ApplicationOrchestration : serviceReady
    deactivate Provisioner
    ApplicationOrchestration -> ApplicationOrchestration : wait(nextService)
end
ApplicationOrchestration --> ApplicationManager
deactivate ApplicationOrchestration


@enduml
