@startuml
Actor "actorName" as A

box "Manage-Applications" #lightblue
participant CLI as CLI
participant Web as Web
participant "c3" as S
A -> CLI : c3-app-list()
CLI -> S : app/list()
A -> Web : app/list()
Web -> S : app/list()
end box

@enduml
