@startuml

skinparam packageStyle rect

package CAADE {
  package "Application Manager" {}
  package "Operations Manager" {}
  package "Application Orchestrator" {}
  package "Application Analyzer" {}
  package "Cloud Broker" {}
  package "Policy Manager" {}
  package "Artifact Repository" {}
  package "Cloud Broker" {}
  package "Data Coordinator" {}
  package "Environment Manager" {}
  package "Identity Manager" {}
  package "Policy Manager" {}
  package "Provision Engine" {}
}

package "SDI Cloud" {
}
package "Public Cloud" {
}

package "Telemetry SNAP" {}

"Cloud Broker" --> "SDI Cloud"
"Cloud Broker" --> "Public Cloud"
"Provision Engine" --> "SDI Cloud"
"Provision Engine" --> "Public Cloud"
"Data Coordinator" --> "SDI Cloud"
"Data Coordinator" --> "Public Cloud"

"SDI Cloud" --> "Telemetry SNAP"
"Public Cloud" --> "Telemetry SNAP"
"Telemetry SNAP" --> "Application Analyzer"
"Telemetry SNAP" --> "Application Orchestrator"
"Application Manager" --> "Policy Manager"
"Application Manager" --> "Application Orchestrator"
"Application Manager" --> "Artifact Repository"
"Application Manager" --> "Environment Manager"
"Operations Manager" --> "Policy Manager"
"Operations Manager" --> "Environment Manager"
"Operations Manager" --> "Artifact Repository"
"Operations Manager" --> "Artifact Repository"
"Policy Manager" --> "Application Orchestrator"
"Environment Manager" --> "Application Orchestrator"
"Environment Manager" --> "Artifact Repository"
"Application Analyzer" --> "Application Orchestrator"
"Policy Manager" --> "Application Analyzer"
"Application Orchestrator" --> "Cloud Broker"
"Application Orchestrator" --> "Provision Engine"
"Application Orchestrator" --> "Data Coordinator"
"Identity Manager" --> "Application Orchestrator"
"Identity Manager" --> "Cloud Broker"
"Artifact Repository" --> "Cloud Broker"
"Artifact Repository" --> "Provision Engine"
"Artifact Repository" --> "Data Coordinator"


@enduml
