@startuml

left to right direction

Actor Dev
cloud "Test" {
  component NodeJS1
  component NodeJS2
  component "NodeJS Worker 1"
  component "NodeJS Worker 2"
  component MongoDB1
  component MongoDB2
  component Redis1
  component Redis2
}
Dev --> Test
@endum
