@startuml

package "cloud-broker" #lightblue {
    interface "cloud-broker" {

    }
    CLI ()-- "cloud-broker" : 5000
    REST ()-- "cloud-broker" : 3000
    Web ()-- "cloud-broker" : 80
}


@enduml
