@startuml

package  "Environment Manager"  #lightblue {
  folder bin #ffffff {
    file environment
  }

  folder Services #ffffff {
    file "env-manager"
  }

  node micro

  node sailsjs
  database DB1

  sailsjs -- DB1
  bin .. sailsjs
  Services .. micro

  micro -- DB1
  sailsjs -> micro
}

@enduml
