@startuml

class ApplicationStack  {
}

class ApplicationStacklet #cccccc {
}

Class Service {
}

Class ServiceTemplate {
}

class Servicelet #cccccc {

}
class Environment {
}

class Image  #cccccc {

}

class RunScript #cccccc {
}

Service *--> Service: subServices
Service *--> ServiceTemplate : templates
ServiceTemplate o--> Environment : env
ServiceTemplate *--> RunScript : scripts
ServiceTemplate o--> Image : image
Servicelet o--> Environment : env
Servicelet o--> ServiceTemplate : template
ApplicationStack *--> "ApplicationStacklet" : stacklets
ApplicationStacklet o--> "Environment" : env
ApplicationStacklet *--> "Servicelet" : servicelets
ApplicationStack o--> "Service" : services

@enduml
