@startuml

left to right direction

skinparam usecase {
  BackgroudnColor #ffffaa
  BackgroundColor<<Main>> #aaffff
}
actor :Operation Manager: <<Component>>
actor :Application Manager: <<Component>>

actor :Cloud Broker: <<Component>>
actor :Provision Engine: <<Component>>
actor :Data Coordinator: <<Component>>
actor :Application Orchestrator: <<Component>>

rectangle "Artifact Repository" {
UseCase MI <<Main>> as "Manage Image"
UseCase MAP <<Main>> as "Manage Application Stack"
UseCase MST <<Main>> as "Manage Service Template"
UseCase FI <<Main>> as "Find Image"
UseCase FAP <<Main>> as "Find Application Stack"
UseCase FST <<Main>> as "Find Service Template"


:Operation Manager: --> MI
:Operation Manager: --> MAP
:Operation Manager: --> MST

:Application Manager: --> FI
:Application Manager: --> FAP
:Application Manager: --> FST
:Application Orchestrator: --> FAP

FI --> :Data Coordinator:
MI <--> :Data Coordinator:
FST --> :Provision Engine:
FST --> :Cloud Broker:
FAP --> :Cloud Broker:
}

@enduml

