@startuml

partition "Application Manager" #dddddd {
  (*) --> "Select Application"
}

partition "Application Analyzer" #dddddd {
  "Get Telemetry" --> "Analyze Application"
}

partition "Application Orchestrator" #lightblue {
  "Select Application" --> "Launch Application"
  "Analyze Application" --> "Rebalance Application"
}

partition "Cloud Broker" #dddddd {
  "Launch Application" --> "Get Resources"
  "Rebalance Application" --> "Get Resources"
}

partition "Application Orchestrator" #lightblue {
  "Get Resources" --> "Deploy Service"
}

partition "Provision Engine" #dddddd {
  "Deploy Service" --> "Deploy Software"
}

@enduml
