@startuml

interface external

package  "app-orchestrator" #lightblue {
  interface internal
  node service
  folder image
}
service -- image
external -- service : 3000
internal -- service : 5000

@enduml
