@startuml
Actor "Application Developer"

"Application Developer" -> "Application Manager" : createApplication(name, ApplicationStack)
activate "Application Manager"
"Application Manager" -> "Application Manager" :findApplicationStack(name) : appStack
create Application
"Application Manager" -> "Application" : new(name, appStack)
"Application Manager" -> "Application" : getJSON()
"Application Developer" <- "Application Manager" : json(Application)
deactivate "Application Manager"

@enduml
