#!/usr/bin/env node

var program = require('commander');

program
  .version("0.2.0")
  .command('create [options]', 'Create an application')
  .command('get [options]', 'Get an application')
  .command('ls', 'List my applications')
  .command('remove <application name>', 'Remove my application')
  .command('show <application name>', 'show details about my application')
  .parse(process.argv);
