#!/usr/bin/env node

var fs = require('fs');
var YAML = require('yamljs');

var program = require('commander');
var Client = require('node-rest-client').Client;
var config = require('./c3-config');

var client = new Client();


program
  .parse(process.argv);

var name = program.args;

var url = config.Url + "/application/get?";

if (name) {
  url += "name=" + name[0];
}

client.get(url, function (data, response) {
  // parsed response body as js object
  if (data.error) {
    console.error("Error:" + data.error);
  }
  else {
    var yamlString = YAML.stringify(data.application, 4);

    fs.writeFile("./c3-app.yaml", yamlString, function (err) {
      if (err) {
        return console.log(err);
      }
      console.log("Application " + name + " was gotten!");
    });
  }
});
