#!/usr/bin/env node

var fs = require('fs');
var YAML = require('yamljs');

var program = require('commander');
var Client = require('node-rest-client').Client;
var config = require('./c3-config');

var client = new Client();

program
  .parse(process.argv);


var name = program.args;

var url = config.Url + "/cloud/show?";

if (name) {
  url += "name=" + name[0];
}
client.get(url, function (data, response) {
  // parsed response body as js object
  if (data.error) {
    console.error("Error:" + data.error);
  }
  else {
    console.log("Name: " + data.name);
    console.log("Type: " + data.type);
  }
});
