#!/usr/bin/env node

var fs = require('fs');
var YAML = require('yamljs');

var program = require('commander');
var Client = require('node-rest-client').Client;
var config = require('./c3-config');

var client = new Client();

program
  .option('-t, --type <type>', 'Create a cloud with the specified Type')
  .parse(process.argv);


program
  .parse(process.argv);

var name = program.args;

var url = config.Url + "/cloud/create?";

if (name) {
  url += "name=" + name[0];
}
if (program.type) {
  url += "&type=" + program.type;
}
client.get(url, function (data, response) {
  // parsed response body as js object
  if (data.error) {
    console.error("Error:" + data.error);
  }
  else {
    console.log("Cloud " + data.name + " was created");
  }
});
