#!/usr/bin/env node

var program = require('commander');
var Client = require('node-rest-client').Client;
var config = require('./c3-config');

var client = new Client();


program
  .option('-e, --env [environment name]', 'Launch command in a specific environment')
  .option('-c, --command <command>', 'Launch command in a specific environment')
  .parse(process.argv);

var services = program.args;

var url = config.Url + "/dev/run?";

if (program.env) {
  url += "env=" + program.env;
}
if (program.command) {
  url += "&command=" + program.command;
}
if (program.args) {
  url += "&services=" + program.args;
}
// direct way
client.get(url, function (data, response) {
  // parsed response body as js object
  console.log(data);
});
