#!/usr/bin/env node

var program = require('commander');
var Client = require('node-rest-client').Client;
var config = require('./c3-config');

var client = new Client();

program
  .option('-e, --env <environmentName>', 'Delete an application stack for the environment')
  .parse(process.argv);

var name = program.args;

var url = config.Url + "/stack/delete?";

if (name) {
  url += "name=" + name[0];
}
if (program.env) {
  url += "&env=" + program.env;
}
client.get(url, function (data, response) {
  // parsed response body as js object
  console.log("Stack " + data.stack.name + " has been deleted for environment " + program.env);
});
