#!/usr/bin/env node

var program = require('commander');
var Client = require('node-rest-client').Client;
var config = require('./c3-config');
var YAML = require('yamljs');
var _ = require('lodash');

var client = new Client();


program
  .option('-e, --env [environment name]', 'Launch application in a specific environment')
  .parse(process.argv);

var services = program.args;

var url = config.Url + "/application/up";
var application = YAML.load('./c3-app.yaml');

if (application.name) {
  url += "?app=" + application.name
}

if (program.env) {
  url += "&env=" + program.env;
}
if (program.args) {
  url += "&services=" + program.args;
}
// direct way
client.get(url, function (data, response) {
  // parsed response body as js object
  console.log("Application " + application.name + " started!");
  _.each(data.instances, function (instance) {
    console.log(instance.id + "\n" + instance.name);
  })
});
