#!/usr/bin/env node

var program = require('commander');

program
  .version("0.2.0")
  .command('create <userName>', 'Create an User')
  .command('update <userName>', 'Update an User')
  .command('ls', 'List my Users')
  .command('remove <userName>', 'Remove an User')
  .command('show <userName>', 'Show details about an User')
  .parse(process.argv);
