@startuml

package "Operations Manager" {
  interface "Operations Manager" {
      ServiceStack createServiceStack()
      Service createServiceTemplate()
  }
}
"CLI" ()-- "Operations Manager"
"REST API" ()-- "Operations Manager"
"Portal" ()-- "Operations Manager"

package "Policy Manager"  #lightgreen {}
package "Environment Manager" #lightgreen {}
package "Artifact Repository" #lightgreen {}

"Operations Manager" --> "Artifact Repository"
"Operations Manager" --> "Policy Manager"
"Operations Manager" --> "Environment Manager"

@enduml
