@startuml

package "Operations-Manager" {
    interface "Operations-Manager" {

    }
    CLI ()-- "Operations-Manager"
    REST ()-- "Operations-Manager"
    Web ()-- "Operations-Manager"

}


@enduml
