@startuml
actor Developer

Developer -> "Application Manager": ApplicationStack selectApplicationStack(String name)
Developer -> "Application Manager": Application createApplication(ApplicationStack, Config[])
Developer -> "Application Manager": Environment selectEnvironment(String name)
Developer -> "Application Manager": ApplicationInstance launchApplication(Application, Environment, Config)
Developer -> "Application Manager": void debugApplication(ApplicationInstance)

@enduml
