@startuml
|Operations Manager|
start
|#ffffaa|OperationsManager|
fork
:Create Compute;
:Modify Compute;
:Remove Compute;
fork again
:Create Storage;
:Modify Storage;
:Remove Storage;
fork again
:Create Network;
:Modify Network;
:Remove Network;
end fork
|Operations Manager|
stop
@enduml
