@startuml

package "Operations Manager" {
  interface "Operations Manager" {
      ApplicationStack createApplicationStack()
      Service createServiceTemplate()
  }
  class ServiceTemplate {

  }
  class ApplicationStack {
  }
}
"CLI" ()-- "Operations Manager"
"REST API" ()-- "Operations Manager"
"Portal" ()-- "Operations Manager"

package "Policy Manager"  #ffffaa {}
package "Environment Manager" #ffffaa {}
package "Artifact Repository" #ffffaa {}

"Operations Manager" --> "Artifact Repository"
"Operations Manager" --> "Policy Manager"
"Operations Manager" --> "Environment Manager"

@enduml
