@startuml

skinparam usecase {
  BackgroudnColor #ffffaa
  BackgroundColor<<Main>> #aaffff
}
left to right direction

actor OM as :Operations Manager: <<Person>>
actor PM as :Policy Manager: <<Component>>
actor EM as :Environment Manager: <<Component>>
actor PE as :Provision Engine: <<Component>>
actor AR as :Artifact Repository: <<Component>>

rectangle "Operations Manager" {
    UseCase MAS <<Main>> as "Manage Application Stack"
    UseCase MST <<Main>> as "Manage Service Template"
    UseCase TST <<Main>> as "Test Service Template"
    UseCase TAS <<Main>> as "Test Application Stack"
    UseCase MAR <<Main>> as "Manage Artifact Repository"
    UseCase MP <<Main>> as "Manage Policies"
    UseCase ME <<Main>> as "Manage Environment"

    OM --> MST
    OM --> MAS
    OM --> TST
    OM --> TAS
    OM --> MAR
    OM --> MP

    MAR --> AR
    TAS --> PE
    MAS --> AR
    TST --> PE
    MST --> AR
    ME --> EM
}

@enduml
