@startuml
|Stack Developer|
start
|#aaffff|ApplicationManager|
:Create Application\nfrom Application Stack;
:Launch Application\non Local Box;
:Launch Application\nin Development Environment;
:Launch Application\nin Test Environment;
:Launch Application\nin Production Environment;
|Stack Developer|
stop
@enduml
