@startuml

package "ApplicationAnalyzer" {
  interface "ApplicationAnalyzer" {
  }
}

CLI ()-- "ApplicationAnalyzer"
"REST API" ()-- "ApplicationAnalyzer"
"Web Portal" ()-- "ApplicationAnalyzer"


@enduml
