@startuml
|Operations Manager|
start
|#lightblue|Common Cloud Core|
:Create Environment;
:Update Environment;
fork
|#lightgreen|Application Developer|
:Find Environment;
:Select Environment;
:Launch Application;
fork again
|#pink|Stack Developer|
:Find Environment;
:Select Environment;
:Update Application Stack;
end fork
|Common Cloud Core|
stop
|Operations Manager|
start
|Common Cloud Core|
if(envoronment not needed) then (yes)
:Delete Environment;
endif
:Update Environment;
stop
@enduml
