@startuml
Actor "Operations Manager" as A

box "Manage Environments" #lightblue
participant CLI as CLI
participant Web as Web
participant "c3" as S
A -> CLI : c3-env-list()
CLI -> S : env/list()
A -> Web : env/list()
Web -> S : env/list()
end box

@enduml
