@startuml
Actor "actorName" as A

box "Manage-Environments" #lightblue
participant CLI as CLI
participant Web as Web
participant "c3" as S
A -> CLI : c3-env-select()
CLI -> S : env/select()
A -> Web : env/select()
Web -> S : env/select()
end box

@enduml
