@startuml

left to right direction

skinparam usecase {
  BackgroudnColor #ffffaa
  BackgroundColor<<Main>> #aaffff
}

actor AO as :Application Orchestrator:
actor SDI as :SDI Cloud:
actor CB as :Cloud Broker:
actor IM as :Identity Manager:

rectangle "Provision Engine" {

UseCase RCS as "Run Command with Service"
UseCase SS as "Start Service"
UseCase KS as "Kill Service"

AO --> RCS
AO --> SS
AO --> KS
RCS --> SDI
SS --> SDI
KS --> SDI
}

@enduml
