@startuml

package "Policy Manager"  #lightgreen {}
package "Environment Manager" #lightgreen {}
package "Application Orchestrator" #lightgreen {}
package "Artifact Repository" #lightgreen {
    class ServiceStack {
    }
}

package "Application Manager" #lightblue {
  interface "Application Manager" {
      stack()
      app()
      service()
  }
  class Application {

  }
  class Service {

  }
  class Config {
    Map values;
  }
  class ApplicationInstance {

  }

  Application "1" *--> "n" Config
  Application "1" o--> "1" ServiceStack
}
"CLI" ()-- "Application Manager"
"REST API" ()-- "Application Manager"
"Portal" ()-- "Application Manager"


"Application Manager" --> "Artifact Repository"
"Application Manager" --> "Policy Manager"
"Application Manager" --> "Application Orchestrator"
"Application Manager" --> "Environment Manager"
@enduml

