@startuml

package "Policy Manager"  #ffffaa {}
package "Environment Manager" #ffffaa {}
package "Application Orchestrator" #ffffaa {}
package "Artifact Repository" #ffffaa {
    class ApplicationStack {
    }
}

package "Application Manager" {
  interface "Application Manager" {
      ApplicationStack selectApplicationStack(String name);
      Environment selectEnvironment(String name);
      Application createApplication(ApplicationStack, Config[])
      void debugApplication(Application)
      void launchApplication(Application, Environment, Config)
      Service createService()
  }
  class Application {

  }
  class Service {

  }
  class Config {
    Map values;
  }
  class ApplicationInstance {

  }

  Application "1" *--> "n" Config
  Application "1" o--> "1" ApplicationStack
}
"CLI" ()-- "Application Manager"
"REST API" ()-- "Application Manager"
"Portal" ()-- "Application Manager"


"Application Manager" --> "Artifact Repository"
"Application Manager" --> "Policy Manager"
"Application Manager" --> "Application Orchestrator"
"Application Manager" --> "Environment Manager"
@enduml
