@startuml
Actor "Application Developer"

"Application Developer" -> "Application Manager" : updateApplication()
activate "Application Manager"
"Application Manager" -> "Application Manager" :findApplicationStack(name) : appStack
"Application Manager" -> "Application" : update(name, appStack)
"Application Manager" -> "Application" : getJSON()
"Application Developer" <- "Application Manager" : json(Application)
deactivate "Application Manager"

@enduml
