@startuml
left to right direction

:Operations Engineer: as Ops

rectangle "Operations Manager" #lightblue {
Ops --> (Create Policy)
Ops --> (Manage Policy)
Ops --> (Manage Running\nApplications)
Ops --> (Plan Capacity)
Ops --> (Manage Users)
Ops --> (Manage Clouds)
Ops --> (Manage Environments)
Ops --> (Map Cloud Resources)
}
@enduml

