@startuml

left to right direction

skinparam usecase {
  BackgroudnColor #ffffaa
  BackgroundColor<<Main>> #aaffff
}
actor :Developer: <<Person>>

actor :Policy Manager: <<Component>>
actor :Environment Manager: <<Component>>
actor :Application Orchestrator: <<Component>>
actor :Artifact Repository: <<Component>>

rectangle "Application Manager" {
UseCase DRA <<Main>> as "Deploy & Run Application
---
On different environments
Locally, Dev, Test, Production
"

UseCase SAS <<Main>> as "Select Application Stack"
UseCase SE <<Main>> as "Select Environment"
UseCase DA as "Debug Application"
UseCase MAS as "Modify Application Stack"
UseCase SAS2 as "Share Application Stack"
UseCase LA <<Main>> as "Launch Application"

Developer --> DRA
Developer --> LA
Developer --> SAS
Developer --> DA
Developer --> MAS
Developer --> SAS2
Developer --> SE <<Main>>
SE --> (Environment Manager)
SAS2 --> (Artifact Repository)
SAS --> (Artifact Repository)
MAS --> (Artifact Repository)
DRA --> (Application Orchestrator)
DA --> (Application Orchestrator)
DRA --> (Policy Manager)
}

@enduml

