@startuml
Actor "actorName" as A

box "Manage-Service" #lightblue
participant CLI as CLI
participant Web as Web
participant "c3" as S
A -> CLI : c3-service-create()
CLI -> S : service/create()
A -> Web : service/create()
Web -> S : service/create()
end box

@enduml
