@startuml
Actor "actorName" as A

box "Manage-Service" #lightblue
participant CLI as CLI
participant Web as Web
participant "c3" as S
A -> CLI : c3-service-update()
CLI -> S : service/update()
A -> Web : service/update()
Web -> S : service/update()
end box

@enduml
