@startuml
|Stack Developer|
start
|#aaffff|ApplicationManager|
:Create Application Stack;
:Modify Application Stack;
:Test the Application Stack;
:Remove Application Stack;
|Stack Developer|
stop
@enduml
