@startuml

left to right direction

Actor Dev
package "Test" #lightblue {
  component NodeJS1 #lightgreen
  component NodeJS2 #lightgreen
  component "NodeJS Worker 1" #lightgreen
  component "NodeJS Worker 2" #lightgreen
  component MongoDB1 #pink
  component MongoDB2 #pink
  component Redis1 #orange
  component Redis2 #orange
}
Dev --> Test
@endum
