@ign

left to right direction

Actor Dev
package "Development" #lightblue {
  component NodeJS #lightgreen
  component "NodeJS Worker" #lightgreen
  component MongoDB #pink
  component Redis #orange
}
Dev --> Development
@enduml
