@startuml

left to right direction

Actor Dev
cloud "Production" {
  component NGInX
  component NodeJS1
  component NodeJS2
  component NodeJS3
  component "NodeJS Worker 1"
  component "NodeJS Worker 2"
  component "NodeJS Worker 3"
  component "NodeJS Worker 4"
  component "NodeJS Worker 5"
  component "NodeJS Worker 6"
  component MongoDB1
  component MongoDB2
  component MongoDB3
  component Redis1
  component Redis2
  component Redis3
}
Dev --> Production

@endum
