@startuml

left to right direction

Actor Dev
package "Production" #lightblue {
  component NGInX #lightyellow
  component NodeJS1 #lightgreen
  component NodeJS2 #lightgreen
  component NodeJS3 #lightgreen
  component "NodeJS Worker 1" #lightgreen
  component "NodeJS Worker 2" #lightgreen
  component "NodeJS Worker 3" #lightgreen
  component "NodeJS Worker 4" #lightgreen
  component "NodeJS Worker 5" #lightgreen
  component "NodeJS Worker 6" #lightgreen
  component MongoDB1 #pink
  component MongoDB2 #pink
  component MongoDB3 #pink
  component Redis1 #orange
  component Redis2 #orange
  component Redis3 #orange
}
Dev --> Production

@endum
