@startuml

skinparam packageStyle rect

package <size:32>C3</size> #lightgray {
    package "<size:24>Portal</size>" as P #lightblue {
        package "Application Manager" { }
        package "Operations Manager" { }
        package "Stack Manager" { }
    }
    package "<size:24>Orchestrator</size>" as O #pink {
        package "Application Orchestrator" { }
        package "Environment Manager" { }
        package "Policy Manager" { }
        package "Application Analytics" { }
    }
    package "<size:24>Registry</size>" as R #lightgreen {
        package "Identity Manager" { }
        package "Artifact Repository" { }
    }

    package "<size:24>Control</size>" as C #lightyellow {
        package "Cloud Broker" { }
        package "Data Coordinator" { }
        package "Provision Engine" { }
    }
}

cloud "<size:24>Private Clouds</size>" as Private #ffffff {
}

cloud "<size:24>Public Clouds</size>" as Public #ffffff {
}

P --> O
P -> R
O -> R
R --> C
O --> C

C --> Private
C --> Public

@enduml

