@startuml

package "Application Analyzer" #ccffff {
    interface CLI
    interface Web
    interface REST
    folder analyzer #ffffff {
        component sailsjs
        component sails.io
    }
    folder bin #ffffff {
      component landscape
      component telemetry
      component app
    }
    folder "app-analyzer" #ffffff {
      component micro as amicro
    }
}
CLI -- app
CLI -- landscape
CLI -- telemetry
app -- REST
landscape -- REST
telemetry -- REST
Web -- sailsjs
Web -- REST
REST -- sailsjs
REST -- amicro

Web -- sails.io

@enduml
